In [2]:
import numpy as np

In [3]:
input_mat =np.matrix([[8,4,2,3,9,1],
             [0,6,4,3,7,10],
             [2,0,1,3,5,8],
             [6,3,1,4,8,2],
             [0,2,4,3,5,9],
             [2,7,9,1,3,5]])
input_mat1 = np.pad(input_mat, 1, 'constant')

 
print(input_mat1)
weight = np.matrix([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]])

[[ 0  0  0  0  0  0  0  0]
 [ 0  8  4  2  3  9  1  0]
 [ 0  0  6  4  3  7 10  0]
 [ 0  2  0  1  3  5  8  0]
 [ 0  6  3  1  4  8  2  0]
 [ 0  0  2  4  3  5  9  0]
 [ 0  2  7  9  1  3  5  0]
 [ 0  0  0  0  0  0  0  0]]


In [4]:
conv_mat = [[0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0]]
conv_mat1=np.pad(conv_mat, 1, 'constant')
print(conv_mat1)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [5]:
for i in range(len(conv_mat1)):
    for j in range(len(conv_mat1[0])):
        conv_mat1[i][j]= np.multiply(input_mat1[i:i+3, j:j+3], weight).sum()
        
print (conv_mat1.shape)

(6, 6)


In [6]:
m, n = conv_mat1.shape
pooled = conv_mat1.reshape(m//2, 2, n//2, 2).max((1, 3))
print(pooled)

[[ 3  4 21]
 [ 2 -1 20]
 [-6  5 16]]


In [7]:
# import skimage.measure from numpy
# skimage.measure.block_reduce(conv_mat1, (3,3), np.max)